### PR TITLE
Plex absolute hama

### PR DESCRIPTION
**Pull request by ksurl**
Add Absolute Series Scanner and Hama.bundle

### CODE REVIEW

**Comment by ksurl** [comment]
was it supposed to go to master? I thought I was looking at the new branch before submitting

**Comment by aptalca** [comment]
It's supposed to be based on the template branch

**Comment by ksurl** [comment]
yeah that's what I thought, but it says I am requesting to merge to master. If it's wrong I can close this and resubmit

**Review by aptalca — APPROVED** [review]

**Comment by aptalca** [comment]
It's all good. I rebased and merged. It's published.

Thanks

**Pull request merged**
