### PR TITLE
Mariadb: mariadb backup adds mariadb-backup to the container

### PR DESCRIPTION
**Pull request by drizuid**
closes linuxserver/docker-mariadb#56

### CODE REVIEW

**Comment by TheCatLady** [comment]
Typo?

> In **_openssh-server_** docker arguments, set an environment variable `DOCKER_MODS=linuxserver/mods:mariadb-mariadb-backup`

**Comment by aptalca** [comment]
no, just a poor result of the naming convention, which is `imagename-modname` in which case the image the mod is for is `mariadb` and the mod name is `mariadb-backup`

**Comment by TheCatLady** [comment]
@aptalca I meant the part I bolded/italicized (openssh-server reference)

**Comment by aptalca** [comment]
oh, haha, yup, clearly I missed it yet again

**Pull request closed without merging**
