### PR TITLE
nextcloud-notify-push: initial commit

### PR DESCRIPTION
**Pull request by melonarc**

### CODE REVIEW

**Comment by aptalca** [comment]
@melonarc 
Can you rebase this on the latest template branch? We made some big changes with regards to multi arch

Thanks

**Comment by melonarc** [comment]
Sure, I left multi-arch as true. The script should choose the right binary for each architecture. Is there anything else I should change to get this merged?

**Comment by aptalca** [comment]
@melonarc can you test this build? `ghcr.io/linuxserver/mods:pull_request_852`

We made a bunch of changes to make things more automated. You no longer need to manually install the Client Push plugin. It also won't need any modifications to reverse proxy setting (once this PR is merged and the NC default site conf is updated: https://github.com/linuxserver/docker-nextcloud/pull/423 )

So please update your Nextcloud site conf to the one from the PR: https://github.com/linuxserver/docker-nextcloud/blob/17e9b76ae2a061ea971322deb446f20d150eb0e8/root/defaults/nginx/site-confs/default.conf.sample
And undo your reverse proxy changes for it.

Let us know how it goes

**Comment by melonarc** [comment]
Hello I tested the new build. Sadly it didn't work for me on my previously used Nextcloud instance. Replaced nginx.conf and restored the Treafik env but got a 400 error. With the old env for Traefik it still works. 

```
melonarc@melonarc:~# ./test_client-x86_64-unknown-linux-musl redacted ...
[2024-04-02 21:43:55.829364 +02:00] INFO [test_client] test_client/src/main.rs:34: Found push server at wss://redacted/push/ws
Error:   × Can't connect to server
  ╰─▶ HTTP error: 400 Bad Request
```

access.log:
```
********* - ******* [02/Apr/2024:21:43:55 +0200] "GET /ocs/v2.php/cloud/capabilities HTTP/2.0" 200 1882 "-" "ureq/2.9.6"
********* - - [02/Apr/2024:21:43:55 +0200] "GET /push/ws HTTP/1.1" 400 43 "-" "-"
```

**Comment by aptalca** [comment]
What does the container log show?

**Comment by melonarc** [comment]
The docker container log:
```
[mod-init] Running Docker Modification Logic
[mod-init] Adding linuxserver/mods:universal-package-install to container
[mod-init] Downloading linuxserver/mods:universal-package-install from lscr.io
[mod-init] Installing linuxserver/mods:universal-package-install
[mod-init] linuxserver/mods:universal-package-install applied to container
[mod-init] Adding linuxserver/mods:nextcloud-memories to container
[mod-init] Downloading linuxserver/mods:nextcloud-memories from lscr.io
[mod-init] Installing linuxserver/mods:nextcloud-memories
[mod-init] linuxserver/mods:nextcloud-memories applied to container
[mod-init] Adding linuxserver/mods:pull_request_852 to container
[mod-init] Downloading linuxserver/mods:pull_request_852 from lscr.io
[mod-init] Installing linuxserver/mods:pull_request_852
[mod-init] linuxserver/mods:pull_request_852 applied to container
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
Initializing nextcloud 28.0.4.1 (this can take a while) ...
Setting permissions
Initializing finished
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│            │ 2024-01-03 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
**** Adding mesa-dri-gallium to OS package install list ****
**** Adding mesa-va-gallium to OS package install list ****
**** Adding perl5 and its deps to package install lists ****
[mod-init] **** Installing all mod packages ****
fetch http://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
(1/11) Installing mesa (23.3.6-r0)
(2/11) Installing llvm17-libs (17.0.5-r0)
(3/11) Installing libelf (0.190-r1)
(4/11) Installing mesa-glapi (23.3.6-r0)
(5/11) Installing mesa-dri-gallium (23.3.6-r0)
(6/11) Installing libxshmfence (1.3.2-r5)
(7/11) Installing mesa-va-gallium (23.3.6-r0)
(8/11) Installing perl (5.38.2-r0)
(9/11) Installing perl-error (0.17029-r2)
(10/11) Installing perl-git (2.43.0-r0)
(11/11) Installing git-perl (2.43.0-r0)
Executing busybox-1.36.1-r15.trigger
OK: 477 MiB in 284 packages
[custom-init] No custom files found, skipping...
**** Making sure the Nextcloud Client Push plugin is installed and enabled ****
notify_push already installed
notify_push already enabled
**** Starting notify-push ****
Connection to localhost (127.0.0.1) 7867 port [tcp/*] succeeded!
**** Setting notify_push server URL to https://redacted/push ****
✓ redis is configured
✓ push server is receiving redis messages
✓ push server can load mount info from database
✓ push server can connect to the Nextcloud server
✓ push server is a trusted proxy
✓ push server is running the same version as the app
  configuration saved
[ls.io-init] done.
```

**Comment by aptalca** [comment]
Thanks, this should take care of it. We need websocket support in Nextcloud's proxy: https://github.com/linuxserver/docker-nextcloud/blob/f3a23468b834151959f9ecfe38ab49b8d737c60b/root/defaults/nginx/site-confs/default.conf.sample#L162-L164

**Pull request merged**
