### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by a-priestley**
ffmpeg path is no longer updatable. Edited the mod README to reflect the requirement to set env `FFMPEG_PATH` to override the run flag.

### CODE REVIEW

**Comment by aptalca** [comment]
The mod can set the env automatically without rewriting the user to add it. 
See here: https://github.com/linuxserver/docker-mods/blob/transmission-trguing/root/etc/s6-overlay/s6-rc.d/init-mod-transmission-trguing-install/run#L4

**Comment by a-priestley** [comment]
The mod has two possible options for the variable though. Would we default to one with the option of using the other?

**Comment by aptalca** [comment]
Oh I hadn't noticed that. Ignore me then

**Comment by junkman690** [comment]
As discussed in #899 we can probably strip this to the one version, and then have the mod set the variable with a check to see if the user has specified one manually. This would maintain backwards compatibility as no additional user setting need to be made to enable to mod to function for existing installs.

**Comment by a-priestley** [comment]
So we don't need to set the variable if intending to use normal rffmpeg? Only for wol_rffmpeg. I can update the PR if so

**Comment by junkman690** [comment]
I was planning to just auto set it to wol rffmpeg if nothing is set by the user var, and document them both as optional in the readme. Need to add the port etc to readme also from previous pulls. I'm away currently but hoping to get time tonight to quickly add a one line if to set the var to wol if not set by user and update readme.

The wol rffmpeg version is just a sys link to the wol bash script which acts as a wrapper to rffmpeg. If running without wol only addition is a single ping to host and a log entry if the host is down.

Having var auto set as a backup will ensure the mod works as previous for anyone who set ffmpeg manually and isn't keeping up with the release notes.

**Comment by a-priestley** [comment]
superseded by #901

**Pull request closed without merging**
