### PR TITLE
lidarr-flac2mp3 update/add workflows

### PR DESCRIPTION
**Pull request by aptalca**

### CODE REVIEW

**Comment by aptalca** [comment]
@TheCaptain989 fyi

**Review by Roxedus — APPROVED** [review]

**Comment by TheCaptain989** [comment]
Template changes it looks like.  I'll test.

**Comment by TheCaptain989** [comment]
Seems to work fine.  Thanks.

**Comment by aptalca** [comment]
Thanks. Changes are mostly template stuff. S6v2 compatibility has been removed (it's been a long time since all our downstream images moved to s6v3). Mod builder workflow has been reworked and now pushes PR builds.

**Pull request merged**
