### PR TITLE
Switch to GHA, add GHCR

### PR DESCRIPTION
**Pull request by nemchik**

### CODE REVIEW

**Review by aptalca — CHANGES_REQUESTED** [review]
This one has various tag customizations

**Comment by nemchik** [comment]
> This one has various tag customizations

Should be handled now.

**Comment by aptalca** [comment]
Pushed image tags need to be updated as well

**Comment by nemchik** [comment]
> Pushed image tags need to be updated as well

Didn't notice that at first. Got it now. Will review the rest.

**Comment by nemchik** [comment]
Wait

**Comment by nemchik** [comment]
Ok now I think I have it.

**Review by aptalca — APPROVED** [review]

**Review by aptalca — APPROVED** [review]

**Pull request merged**
