### PR TITLE
Code server java11

### PR DESCRIPTION
**Pull request by EGOISTK21**
Add java11 mod for code-server

### CODE REVIEW

**Review by aptalca — APPROVED** [review]

**Comment by binarymelon** [comment]
@aptalca @EGOISTK21 Could this be universal?

**Comment by binarymelon** [comment]
Easily add java to other containers.  Is there any reason why this wouldn't work?  I applied it to the calibre container and it seems to work fine.

**Comment by binarymelon** [comment]
For calibre specifically, it's because there is a plugin that has a java dependency.

https://github.com/w3c/epubcheck

**Comment by aptalca** [comment]
Gotcha, thanks. Then yes, it's safe to use this mod on calibre (but only the `latest` tag. It won't work on the `arch` tag as it is archlinux based).

**Pull request merged**
