### PR TITLE
Remove codecs

### PR DESCRIPTION
**Pull request by mouzzampk2014-zz**

### CODE REVIEW

**Review by aptalca — APPROVED** [review]

**Review by aptalca — CHANGES_REQUESTED** [review]
Please add back the info on how to enable this mod
Also, please squash the commits into one

**Comment by Roxedus** [comment]
@mouzzampk2014

**Comment by drizuid** [comment]
@mouzzampk2014

**Comment by aptalca** [comment]
no activity, closing

**Pull request closed without merging**
