### PR TITLE
Jellyfin: amd Initial release

### PR DESCRIPTION
**Pull request by PascalMinder**
Adds necessary libraries to the Jellyfin container to be able to use VAAPI on AMD graphic cards

https://github.com/linuxserver/docker-jellyfin/issues/51

### CODE REVIEW

**Review by aptalca — CHANGES_REQUESTED** [review]
- Please follow the directions listed here: https://github.com/linuxserver/docker-mods/tree/template#mod-creation-instructions
Use the template branch as your starting point, not master
- mod-list.yml does not belong here
- You can use the `Dockerfile` as is, by just updating the maintainer label, no need to use `Dockerfile.complex`
- Don't do `apt-get upgrade`
- You can check for the repo and the packages before adding/installing so it doesn't slow down start with unnecessary updates of package cache

**Comment by PascalMinder** [comment]
Hi @aptalca 
Thanks for your initial review. I pushed a new commit to the PR. I hope I have followed all the instructions this time.

**Comment by aptalca** [comment]
@PascalMinder please allow maintainer to push changes. I have a bunch of edits. Thanks

**Comment by PascalMinder** [comment]
> @PascalMinder please allow maintainer to push changes. I have a bunch of edits. Thanks

I have enabled it. Thanks.

**Review by aptalca — APPROVED** [review]

**Comment by aptalca** [comment]
Thanks @PascalMinder it is now published at https://mods.linuxserver.io/?mod=jellyfin

**Pull request merged**
