### PR TITLE
switch to hybrid (radarr-striptracks)

### PR DESCRIPTION
**Pull request by aptalca**
fyi @thecaptain989

### CODE REVIEW

**Comment by TheCaptain989** [comment]
I'm fine with this one as well.

**Comment by aptalca** [comment]
@TheCaptain989 This PR is locally built and pushed to `aptalca/mods:radarr-striptracks` and if you can test with the latest radarr and confirm, we'll merge.

Thanks

**Comment by TheCaptain989** [comment]
> @TheCaptain989 This PR is locally built and pushed to `aptalca/mods:radarr-striptracks` and if you can test with the latest radarr and confirm, we'll merge.
> 
> Thanks

I'll get started!

**Comment by TheCaptain989** [comment]
@aptalca, I've completed my testing.  Everything works as expected on the latest sonarr container.
I discovered a bug in my own code in radarr, but it is trivial and doesn't affect operation.  I've got it working in dev already.

**Review by thespad — APPROVED** [review]

**Pull request merged**
