### PR TITLE
Fix issue with logs that contains space in the path

### PR DESCRIPTION
**Pull request by piotrmaj**
Fix issue with logs that contains space in the path: wrap tail argument in quotes to prevent the faulty behavior as per https://stackoverflow.com/a/43793896

### CODE REVIEW

**Comment by aptalca** [comment]
This will break multiple log paths

Try escaping the space in your var instead

**Comment by piotrmaj** [comment]
> This will break multiple log paths
> 
> Try escaping the space in your var instead

I tried that at the begging but couldn't make it work. 

```
- name: LOGS_TO_STDOUT 
  value: "/config/Library/Application\ Support/Plex\ Media\ Server/Logs/Plex\ Crash\ Uploader.log|/config/Library/Application\ Support/Plex\ Media\ Server/Logs/Plex\ Crash\ Uploader.log"`
```
Results in
```
Starting Plex Media Server. . . (you can ignore the libusb_init error)
Executing: tail -F /config/Library/Application Support/Plex Media Server/Logs/Plex Crash Uploader.log /config/Library/Application Support/Plex Media Server/Logs/Plex Crash Uploader.log
tail: cannot open '/config/Library/Application' for reading: No such file or directory
tail: cannot open 'Support/Plex' for reading: No such file or directory
tail: cannot open 'Media' for reading: No such file or directory
tail: cannot open 'Server/Logs/Plex' for reading: No such file or directory
tail: cannot open 'Crash' for reading: No such file or directory
tail: cannot open 'Uploader.log' for reading: No such file or directory
tail: cannot open '/config/Library/Application' for reading: No such file or directory
tail: cannot open 'Support/Plex' for reading: No such file or directory
tail: cannot open 'Media' for reading: No such file or directory
tail: cannot open 'Server/Logs/Plex' for reading: No such file or directory
tail: cannot open 'Crash' for reading: No such file or directory
tail: cannot open 'Uploader.log' for reading: No such file or directory
```

And version without quotes
```
```
results in
```
Starting Plex Media Server. . . (you can ignore the libusb_init error)
Executing: tail -F /config/Library/Application\ Support/Plex\ Media\ Server/Logs/Plex\ Crash\ Uploader.log /config/Library/Application\ Support/Plex\ Media\ Server/Logs/Plex\ Crash\ Uploader.log
tail: cannot open '/config/Library/Application\' for reading: No such file or directory
tail: cannot open 'Support/Plex\' for reading: No such file or directory
tail: cannot open 'Media\' for reading: No such file or directory
tail: cannot open 'Server/Logs/Plex\' for reading: No such file or directory
tail: cannot open 'Crash\' for reading: No such file or directory
tail: cannot open 'Uploader.log' for reading: No such file or directory
tail: cannot open '/config/Library/Application\' for reading: No such file or directory
tail: cannot open 'Support/Plex\' for reading: No such file or directory
tail: cannot open 'Media\' for reading: No such file or directory
tail: cannot open 'Server/Logs/Plex\' for reading: No such file or directory
tail: cannot open 'Crash\' for reading: No such file or directory
tail: cannot open 'Uploader.log' for reading: No such file or directory
```

Current solution with parsing to array seems to work but I'm not very good with bash so maybe it has some other downsides

```
- name: LOGS_TO_STDOUT 
  value: "/config/Library/Application Support/Plex Media Server/Logs/Plex Crash Uploader.log|/config/Library/Application Support/Plex Media Server/Logs/Plex DLNA Server.log"
```
result:
```
Starting Plex Media Server. . . (you can ignore the libusb_init error)
Executing: tail -F /config/Library/Application Support/Plex Media Server/Logs/Plex Crash Uploader.log /config/Library/Application Support/Plex Media Server/Logs/Plex DLNA Server.log
==> /config/Library/Application Support/Plex Media Server/Logs/Plex Crash Uploader.log <==
Nov 05, 2023 18:04:58.225 [140202741205816] INFO - Crash Uploader - Platform: Linux ServerUUID: 7eaef04630e39c9d93cca711912451534c8bd7ab UserId: maju1993@o2.pl Version: 1.32.7.7621-871adbd44
Nov 05, 2023 18:04:58.226 [140202741205816] INFO - Pre-processed minidump directory: /config/Library/Application Support/Plex Media Server/Crash Reports/1.32.7.7621-871adbd44
Nov 05, 2023 18:04:58.226 [140202741205816] INFO - Post-processed minidump directory: /tmp
Nov 05, 2023 18:04:58.216 [140202773784584] INFO - Crash Uploader - Processing Complete.
==> /config/Library/Application Support/Plex Media Server/Logs/Plex DLNA Server.log <==
Jul 15, 2021 20:39:47.630 [0x7f5436bfd700] DEBUG - Mapped object 52557847-e9d7-49f6-b9fa-e6b54923190d_99 to  part 0 on server 
Jul 15, 2021 20:39:47.634 [0x7f5436bfd700] DEBUG - OnBrowseDirectChildren returning success with 4 objects of 4 total
Jul 15, 2021 20:39:48.642 [0x7f5436bfd700] DEBUG - OnBrowseDirectChildren for '52557847-e9d7-49f6-b9fa-e6b54923190d_99' with filter 'res@resolution,res@nrAudioChannels,res@sampleFrequency,res@bitrate,dc:creator,res@dlna:cleartextSize,dc:date,upnp:genre,res,res@duration,res@size,upnp:albumArtURI,upnp:originalTrackNumber,upnp:album,upnp:artist,upnp:author' and sort '', paged as 0 + 30
Jul 15, 2021 20:39:48.642 [0x7f5436bfd700] DEBUG - Mapped client to generic profile: SOAPAction: "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"; DLNADeviceName.lge.com: %5bLG%5d%20webOS%20TV%20OLED55B9SLA; User-Agent: Linux/4.4.84-169.gld4tv.4 UPnP/1.0 LGE WebOS TV LGE_DLNA_SDK/1.6.0/05.10.15 DLNADOC/1.50; Host: 192.168.0.52:32469; Content-Length: 713; Content-Type: text/xml; charset="utf-8"
Jul 15, 2021 20:39:48.643 [0x7f5436bfd700] DEBUG - Mapped object 52557847-e9d7-49f6-b9fa-e6b54923190d_99 to  part 0 on server 
Jul 15, 2021 20:39:48.646 [0x7f5436bfd700] DEBUG - OnBrowseDirectChildren returning success with 4 objects of 4 total
Jul 15, 2021 20:39:49.654 [0x7f5436bfd700] DEBUG - OnBrowseDirectChildren for '52557847-e9d7-49f6-b9fa-e6b54923190d_99' with filter 'res@resolution,res@nrAudioChannels,res@sampleFrequency,res@bitrate,dc:creator,res@dlna:cleartextSize,dc:date,upnp:genre,res,res@duration,res@size,upnp:albumArtURI,upnp:originalTrackNumber,upnp:album,upnp:artist,upnp:author' and sort '', paged as 0 + 30
Jul 15, 2021 20:39:49.654 [0x7f5436bfd700] DEBUG - Mapped client to generic profile: SOAPAction: "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"; DLNADeviceName.lge.com: %5bLG%5d%20webOS%20TV%20OLED55B9SLA; User-Agent: Linux/4.4.84-169.gld4tv.4 UPnP/1.0 LGE WebOS TV LGE_DLNA_SDK/1.6.0/05.10.15 DLNADOC/1.50; Host: 192.168.0.52:32469; Content-Length: 713; Content-Type: text/xml; charset="utf-8"
Jul 15, 2021 20:39:49.654 [0x7f5436bfd700] DEBUG - Mapped object 52557847-e9d7-49f6-b9fa-e6b54923190d_99 to  part 0 on server 
Jul 15, 2021 20:39:49.658 [0x7f5436bfd700] DEBUG - OnBrowseDirectChildren returning success with 4 objects of 4 total
```

**Comment by piotrmaj** [comment]
@aptalca good point about the array name. Thanks for the review and for the work on linuxserver images, they are awesome! ☺️ 

I noticed that for some reason docker build failed now due to 
`failed to solve: failed to authorize: failed to fetch oauth token: Post "https://auth.docker.io/token": EOF`
but it doesn't seem to be related to my changes

**Comment by aptalca** [comment]
Thanks. Docker hub has been having issues today.

**Review by aptalca — APPROVED** [review]

**Pull request merged**
