### PR TITLE
build: change upstream to a maintained fork of transmission-web-control

### PR DESCRIPTION
**Pull request by FujiZ**
Currently the original project is not under active development, so we change the upstream to a maintained fork of it.

### CODE REVIEW

**Comment by FujiZ** [comment]
It seems that the github action uses an old version of `BuildImage.yml` in set-vars stage, so that the `MOD_VERSION` is wrong (https://github.com/linuxserver/docker-mods/actions/runs/7149850044/job/19472501578?pr=796#step:2:7)

@aptalca Do you any idea how to resolve this?

**Comment by thespad** [comment]
The mod version logic for live builds is run from a Jenkins pipeline, so please don't add extra conditional logic to the workflow files, just update the repo URL. We'll update it when the PR is ready to be merged.

**Comment by FujiZ** [comment]
> The mod version logic for live builds is run from a Jenkins pipeline, so please don't add extra conditional logic to the workflow files, just update the repo URL. We'll update it when the PR is ready to be merged.

Got it. I have reverted the changes

**Comment by FujiZ** [comment]
@thespad Could you please provide some suggestions for this PR?

**Review by thespad — APPROVED** [review]

**Comment by thespad** [comment]
Sorry, been busy and haven't had a chance to get back to this. All looks fine and I'm happy to merge, at which point the updated workflow should grab the correct upstream version, but I'll double check that the build runs correctly.

**Pull request merged**
