### PR TITLE
switch to hybrid (universal-wait-for-internet)

### PR DESCRIPTION
**Pull request by aptalca**

### CODE REVIEW

**Comment by aptalca** [comment]
locally tested

**Review by thespad — APPROVED** [review]

**Review by thespad — APPROVED** [review]
Should this be added to the deps for init-mods-end?

**Review by thespad — COMMENTED** [review]
Should this be added to the deps for init-mods-end?

Especially as it's waiting for something - otherwise the package install step will run in parallel, which will then allow init-mods-end to trigger.

**Comment by aptalca** [comment]
it's a typo. the folder `init-mods` should have been `init-mods-end`

**Comment by thespad** [comment]
As in before *everything* or just before other mods? Right now it'll run immediately but will only stop mod processing (and everything after it).

**Comment by aptalca** [comment]
mostly everything. The v2 version was running as `15-wait-for-internet`. I didn't see a more appropriate anchor. We should probably deprecate this

**Pull request merged**
