### PR TITLE
transmission: env-var-settings initial release

### PR DESCRIPTION
**Pull request by josevh**
This mod allows for Transmission settings to be set via ENV vars.

The script is written in Python 3. The transmission base image comes with Python so it wasn't added as a dependency.

### CODE REVIEW

**Comment by aptalca** [comment]
Thanks for the PR. 
The code looks fine to me, but I don't have a transmission setup to test it on. Can you test the mod pushed to `ghcr.io/linuxserver/mods:pull_request_718` and confirm it works as expected?

**Review by aptalca — APPROVED** [review]

**Comment by josevh** [comment]
So I thought a good test would be
```
docker run --rm \
  --name=transmission \
  -v /tmp/config:/config \
  -e DOCKER_MODS=ghcr.io/linuxserver/mods:pull_request_718 \
  -e TRANSMISSION_RPC_URL=PR_718_TEST \
  lscr.io/linuxserver/transmission:latest \
  grep rpc-url /config/settings.json
```

And it led me to realize that the `settings.json` file doesn't exist on the first run of the container. Which is unfortunate because the script uses the contents of the file to identify valid settings. 🤔

**Comment by thespad** [comment]
It does, we copy it [here](https://github.com/linuxserver/docker-transmission/blob/master/root/etc/s6-overlay/s6-rc.d/init-transmission-config/run#L8-L11), which will run before mod init does.

**Comment by josevh** [comment]
Worked when I added `init-transmission-config` as a dependency of the mod. Unsure why it was needed.
Pushing the change in a minute.

**Comment by josevh** [comment]
With latest pull of `ghcr.io/linuxserver/mods:pull_request_718` including the last force-pushed changes.

For command
```
docker run --rm \
  -e DOCKER_MODS=ghcr.io/linuxserver/mods:pull_request_718 \
  -e "TRANSMISSION_RPC_URL=/PR718_TEST/" \
  lscr.io/linuxserver/transmission:latest \
  grep rpc-url /config/settings.json
```

Get output
```
...
[custom-init] No custom files found, skipping...
[ls.io-init] done.
    "rpc-url": "/PR718_TEST/",
...
```

**Comment by thespad** [comment]
> Worked when I added `init-transmission-config` as a dependency of the mod. Unsure why it was needed. Pushing the change in a minute.

Hmm, that shouldn't be necessary. init-mods depends on init-config-end, which depends on init-crontabs-config, which depends on init-transmission-config so that relationship should already be there.

**Comment by josevh** [comment]
Might have been bad testing on my part?
It now works without that dependency.

```
docker run --rm \
  -e DOCKER_MODS=ghcr.io/linuxserver/mods:pull_request_718 \
  -e "TRANSMISSION_RPC_URL=/PR718_TEST_3/" \
  lscr.io/linuxserver/transmission:latest \
  grep rpc-url /config/settings.json
```

results in
```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding linuxserver/mods:pull_request_718 to container
[mod-init] Downloading linuxserver/mods:pull_request_718 from lscr.io
[mod-init] Installing linuxserver/mods:pull_request_718
[mod-init] linuxserver/mods:pull_request_718 applied to container
...
Applying transmission env-var-settings mod...
From ENV setting 'rpc-url'='/PR718_TEST_3/'.
Transmission settings file saved.
Applied transmission env-var-settings mod successfully.
[custom-init] No custom files found, skipping...
[ls.io-init] done.
    "rpc-url": "/PR718_TEST_3/",
```

**Comment by aptalca** [comment]
Your test grep is probably running too early. Start the container as usual, wait until init is completed, and then check the settings file

**Comment by josevh** [comment]
Testing via your suggestion confirms that it is working without the dependency on `init-transmission-config`.

```
$ docker run -d \
  --name transmission-test \
  -e DOCKER_MODS=ghcr.io/linuxserver/mods:pull_request_718 \
  -e "TRANSMISSION_RPC_URL=/PR718_TEST_4/" \
  lscr.io/linuxserver/transmission:latest
```
15 seconds..
```
$ docker logs -n 5 transmission-test 
From ENV setting 'rpc-url'='/PR718_TEST_4/'.
Transmission settings file saved.
Applied transmission env-var-settings mod successfully.
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

```
$ docker exec -it transmission-test grep rpc-url /config/settings.json
    "rpc-url": "/PR718_TEST_4/",
```

**Pull request merged**
