### PR TITLE
universal: internationalization initial release

### PR DESCRIPTION
**Pull request by thelamer**
Adds internationalization support to any image for Alpine/Debian/Fedora/Ubuntu/Arch. 

Allows the user to change the lang in the container to a list laid out in the readme.

### CODE REVIEW

**Comment by thelamer** [comment]
Still testing FYI

**Comment by aptalca** [comment]
Heads up, it pushed it to this tag for testing:
https://github.com/linuxserver/docker-mods/pkgs/container/mods/85299822?tag=pull_request_627

**Comment by thelamer** [comment]
This one is G2G now. Tested across all distros. Just needs review. The non Alpine webtops will need to waterfall on next build but the alpine images work as is IE: 

```
docker run --rm -it -p 3000:3000 --shm-size="1gb" -e LC_ALL=ko_KR.UTF-8 -e DOCKER_MODS="ghcr.io/linuxserver/mods:pull_request_627" linuxserver/webtop bash
```

Or 

```
docker run --rm -it -p 3000:3000 --shm-size="1gb" -e LC_ALL=ko_KR.UTF-8 -e DOCKER_MODS="ghcr.io/linuxserver/mods:pull_request_627" linuxserver/chromium bash
```

**Comment by aptalca** [comment]
Can you add back the permissions and the issue pr tracker workflows? It looks like they got deleted during the rebase

**Comment by thelamer** [comment]
> Can you add back the permissions and the issue pr tracker workflows? It looks like they got deleted during the rebase

Yep, my bad deleted them as I was using an old mod for reference. 

Added.

**Review by aptalca — APPROVED** [review]

**Pull request merged**
