### PR TITLE
radarr: striptracks release 2.7.1

### PR DESCRIPTION
**Pull request by TheCaptain989**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [X] I have read the [contributing](https://github.com/linuxserver/docker-mods/blob/a494d309f5e530aa3f1cb3a14b7fd0db4fc0f14b/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

- **New** Uses semantic versioning
- Light editing of README
  - Added GHCR pull counts
- Updated Docker image labeling

## Benefits of this PR and context:

- **Fixes** TheCaptain989/radarr-striptracks#73

## How Has This Been Tested?

Separate Docker development environment, with custom test script plus manual testing.
Functional changes deployed from [development repo](https://github.com/TheCaptain989/radarr-striptracks) and running for 3 weeks in personal environment.

## Source / References:

None.

### CODE REVIEW

**Comment by TheCaptain989** [comment]
Please let me know if the hotio bits are appropriate.  I went back and forth with it before submitting the PR.

**Comment by TheCaptain989** [comment]
> I talked to the team and the general feeling was that the hotio script and the instructions are out of place here. Hotio has his own instructions in their docs for custom scripts. This mod repo is specifically for lsio images and is the lsio official repo.

Understood.  Let me remove those pieces.  It's pretty easy.

**Comment by TheCaptain989** [comment]
Done.  I've removed all references to hotio.  Thanks for the consideration.

**Review by aptalca — APPROVED** [review]
Awesome. Looks great, thanks.

**Pull request merged**
