### PR TITLE
Nextcloud mediadc

### PR DESCRIPTION
**Pull request by JonathanTreffler**
The mediaDC Nextcloud App requires a bunch of extra dependencies.
This Mod installs any required and optional packages.

### The MediaDC Self Check says the dependencies are fine when using this mod:
image
image

# TODO
- [x] Dependency Install Script
- [x] Github Action edits
- [x] README update
- [x] Testing on x86-64
- [ ] Testing on arm64 (Who can help ?)
- [ ] Testing on armhf (Who can help ?)

This is largely based on the [docker example](https://github.com/andrey18106/mediadc-docker-example) provided by the MediaDC devs.

### CODE REVIEW

**Comment by JonathanTreffler** [comment]
For testing i pushed it to DockerHub: DOCKER_MODS=tessypowder/linuxserver-mod-nextcloud-mediadc:latest
I will delete that, when this is merged and the Github Action kicks in.

**Comment by JonathanTreffler** [comment]
I will need help testing this mod on arm64 and armhf.

**Comment by aptalca** [comment]
you can test on armhf and aarch64 via qemu: https://github.com/linuxserver/docker-nextcloud#building-locally
Just run the following once on your docker host:
`docker run --rm --privileged multiarch/qemu-user-static:register --reset`
And after that, you can run any arch image by specifying the relevant tag:
`docker run . . . . . lscr.io/linuxserver/nextcloud:arm32v7-latest` or `arm64v8-latest`

**Comment by aptalca** [comment]
These pip packages take a long time to compile on arm. I'll get our wheelie to build wheels for them so they can be quickly pulled from our repo.

**Comment by aptalca** [comment]
Just a heads up, pillow_heif was not building on alpine armhf. I'm working with the upstream dev on that

**Comment by aptalca** [comment]
@JonathanTreffler I just pushed some changes. Now it installs correctly on all three arches. On armhf, unfortunately it needs to compile pillow_heif from source and it takes a while, but next month I'll be able to add it to our wheel builder so it will install from prebuilt wheel.

**Review by aptalca — APPROVED** [review]

**Pull request merged**
