### PR TITLE
switch to hybrid (lidarr-flac2mp3)

### PR DESCRIPTION
**Pull request by aptalca**
fyi @thecaptain989

### CODE REVIEW

**Comment by TheCaptain989** [comment]
I'll be able to take a look at this in a couple days.

**Comment by aptalca** [comment]
No worries, I just wanted to give you a heads up about making the mod compatible with s6v3, which is quite a bit different. This PR will make it compatible with both v2 and v3. Our baseimages are being updated to support v3 and the mods will all be made compatible before the downstream images are converted to v3. After that point, everything will be v3

**Comment by TheCaptain989** [comment]
Okay, I think I'm caught up and I understand.
There's one tiny change that I would make to BuildImage.yml to properly support s6v3, but not having it doesn't break any functionality.

**Comment by aptalca** [comment]
@TheCaptain989 I think I see what you're referring to. I just pushed an update in the last commit.

I also locally built this PR and pushed to `aptalca/mods:lidarr-flac2mp3`, if you could test that with the latest lidarr image and confirm it's working fine, we'll go ahead and merge this.

Thanks

**Comment by TheCaptain989** [comment]
> @TheCaptain989 I think I see what you're referring to. I just pushed an update in the last commit.
> 
> I also locally built this PR and pushed to `aptalca/mods:lidarr-flac2mp3`, if you could test that with the latest lidarr image and confirm it's working fine, we'll go ahead and merge this.
> 
> Thanks

Cool!  I'll get started on testing.

**Comment by TheCaptain989** [comment]
@aptalca, I finished my testing.
The mod and my script work fine!  The only thing I found is that my versioning did not come through, which I would expect since it was built locally.

**Comment by aptalca** [comment]
oh yeah, the versioning is handled in the workflow and gets injected as a build arg (I didn't inject it when I built locally)

**Review by thespad — APPROVED** [review]

**Pull request merged**
